export interface FarmActivity {
  id: string
  stage: 'Sowing' | 'Irrigation' | 'Fertilization' | 'Pest Monitoring' | 'Harvest' | 'Custom'
  title: string
  description: string
  recommendation: string
  dayOffset: number // Days from sowing date
  durationDays?: number
  completed: boolean
  customDate?: string // Farmer adjusted date (YYYY-MM-DD)
  iconType: 'sowing' | 'irrigation' | 'fertilizer' | 'pest' | 'harvest' | 'general'
}

export interface CropTemplate {
  id: string
  name: string
  category: 'Cereal' | 'Pulse' | 'Cash Crop' | 'Vegetable' | 'Oilseed'
  defaultSeason: 'Kharif' | 'Rabi' | 'Zaid'
  durationDays: number
  description: string
  activities: Omit<FarmActivity, 'id' | 'completed' | 'customDate'>[]
}

export const CROP_TEMPLATES: CropTemplate[] = [
  {
    id: 'wheat',
    name: 'Wheat (गेहूं / ઘઉં)',
    category: 'Cereal',
    defaultSeason: 'Rabi',
    durationDays: 120,
    description: 'Major staple Rabi crop requiring cool weather and timely irrigation stages.',
    activities: [
      {
        stage: 'Sowing',
        title: 'Land Preparation & Seed Sowing',
        description: 'Plough field 2-3 times to fine tilth. Treat seeds with Trichoderma (5g/kg) or Carbendazim (2g/kg).',
        recommendation: 'Sow at 4-5 cm depth with row spacing of 20-22 cm. Ideal seed rate: 100-120 kg/ha.',
        dayOffset: 0,
        durationDays: 5,
        iconType: 'sowing',
      },
      {
        stage: 'Irrigation',
        title: 'Crown Root Initiation (CRI) Irrigation',
        description: 'Crucial 1st irrigation at 20-25 days after sowing. Missing this can reduce yield by up to 25%.',
        recommendation: 'Ensure light and uniform watering without waterlogging.',
        dayOffset: 21,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Fertilization',
        title: '1st Top Dressing & Weed Control',
        description: 'Apply 1st split dose of Urea (50-60 kg/acre). Spray 2,4-D or Clodinafop for broadleaf/grassy weeds.',
        recommendation: 'Apply Urea just after the 1st irrigation when soil has adequate moisture.',
        dayOffset: 30,
        durationDays: 4,
        iconType: 'fertilizer',
      },
      {
        stage: 'Irrigation',
        title: 'Tillering & Jointing Irrigation',
        description: '2nd irrigation cycle to support active tiller production and healthy root establishment.',
        recommendation: 'Check soil moisture before irrigating. Avoid excess ponding.',
        dayOffset: 45,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Yellow/Brown Rust & Aphid Inspection',
        description: 'Inspect underside of leaves for yellow powdery pustules or aphid colonies on spikes.',
        recommendation: 'If rust is spotted, spray Propiconazole 25% EC (Tilt) @ 1 ml/L. Use yellow sticky traps for aphids.',
        dayOffset: 65,
        durationDays: 7,
        iconType: 'pest',
      },
      {
        stage: 'Fertilization',
        title: 'Booting Stage Foliar Nutrition',
        description: 'Foliar spray of 13:0:45 (Potassium Nitrate) @ 10g/L or 19:19:19 to improve grain size and weight.',
        recommendation: 'Spray in cool evening hours to avoid leaf scorch.',
        dayOffset: 75,
        durationDays: 3,
        iconType: 'fertilizer',
      },
      {
        stage: 'Irrigation',
        title: 'Grain Filling (Milking) Irrigation',
        description: 'Final critical watering during grain filling. Protects crop from premature drying during temperature rise.',
        recommendation: 'Avoid irrigating during high wind velocity to prevent lodging (crop falling).',
        dayOffset: 85,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Harvest',
        title: 'Harvesting & Threshing',
        description: 'Crop turns golden yellow and grain moisture drops below 14%.',
        recommendation: 'Harvest during dry sunny weather. Dry grains properly before long-term storage in clean bags.',
        dayOffset: 120,
        durationDays: 7,
        iconType: 'harvest',
      },
    ],
  },
  {
    id: 'rice',
    name: 'Rice / Paddy (धान / ચોખા)',
    category: 'Cereal',
    defaultSeason: 'Kharif',
    durationDays: 130,
    description: 'High-water cereal crop grown widely during monsoon across diverse agro-climatic zones.',
    activities: [
      {
        stage: 'Sowing',
        title: 'Nursery Bed Sowing & Seed Treatment',
        description: 'Soak seeds in salt solution to eliminate chaffy seeds. Treat with Pseudomonas or Carbendazim.',
        recommendation: 'Prepare raised nursery beds. Keep moist for 20-25 days until 4-leaf seedling stage.',
        dayOffset: 0,
        durationDays: 4,
        iconType: 'sowing',
      },
      {
        stage: 'Sowing',
        title: 'Puddling & Main Field Transplantation',
        description: 'Puddle main field thoroughly. Transplant 2-3 seedlings per hill at 20x15 cm spacing.',
        recommendation: 'Incorporate basal DAP (50 kg/acre) and Zinc Sulphate (10 kg/acre) during last puddling.',
        dayOffset: 25,
        durationDays: 5,
        iconType: 'sowing',
      },
      {
        stage: 'Irrigation',
        title: 'Vegetative Water Management',
        description: 'Maintain shallow standing water (2-3 cm) for 3 weeks post transplantation to suppress weeds.',
        recommendation: 'Practice Alternate Wetting and Drying (AWD) to save water and reduce methane emissions.',
        dayOffset: 35,
        durationDays: 20,
        iconType: 'irrigation',
      },
      {
        stage: 'Fertilization',
        title: 'Tillering Stage Top Dressing',
        description: 'Apply 1st top dressing of Urea (35 kg/acre) along with Neem cake or bio-fertilizers.',
        recommendation: 'Broadcast when leaf canopy is dry to prevent fertilizer granules from sticking to leaves.',
        dayOffset: 45,
        durationDays: 3,
        iconType: 'fertilizer',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Stem Borer & Leaf Folder Surveillance',
        description: 'Look for dead hearts in young plants or white ear heads at heading stage. Check for leaf folding.',
        recommendation: 'Install pheromone traps @ 5/acre. Spray Cartap Hydrochloride 50 SP @ 2g/L if threshold is exceeded.',
        dayOffset: 60,
        durationDays: 10,
        iconType: 'pest',
      },
      {
        stage: 'Fertilization',
        title: 'Panicle Initiation Top Dressing',
        description: 'Apply remaining split dose of Urea (25 kg/acre) and Muriate of Potash (MOP 15 kg/acre).',
        recommendation: 'Potash strengthens stems and enhances grain luster and disease resistance.',
        dayOffset: 75,
        durationDays: 3,
        iconType: 'fertilizer',
      },
      {
        stage: 'Harvest',
        title: 'Field Draining & Final Harvest',
        description: 'Drain standing water completely 10-12 days before anticipated harvest date.',
        recommendation: 'Harvest when 80-85% grains in panicles have turned straw golden.',
        dayOffset: 125,
        durationDays: 7,
        iconType: 'harvest',
      },
    ],
  },
  {
    id: 'cotton',
    name: 'Cotton (कपास / કપાસ)',
    category: 'Cash Crop',
    defaultSeason: 'Kharif',
    durationDays: 160,
    description: 'Long-duration fiber crop thriving in deep black soils with warm temperatures.',
    activities: [
      {
        stage: 'Sowing',
        title: 'Ridge & Furrow Sowing',
        description: 'Sow delinted seeds on ridges at 90x60 cm spacing. Treat seeds with Imidacloprid for sucking pests.',
        recommendation: 'Apply well-decomposed FYM (5 tonnes/ha) + basal NPK 10:26:26 (50 kg/acre).',
        dayOffset: 0,
        durationDays: 4,
        iconType: 'sowing',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Early Sucking Pest Inspection',
        description: 'Check young leaves for Jassids, Thrips, and Aphids causing leaf curling or yellow margins.',
        recommendation: 'Spray Neem oil 1500 ppm @ 3 ml/L or Flonicamid 50 WG if nymph count exceeds 5 per leaf.',
        dayOffset: 25,
        durationDays: 7,
        iconType: 'pest',
      },
      {
        stage: 'Fertilization',
        title: 'Square Formation Top Dressing',
        description: 'Apply 1st split Urea (30 kg/acre) + Potassium (15 kg/acre) at square initiation.',
        recommendation: 'Earthing up should be performed along with fertilizer application to support root anchoring.',
        dayOffset: 50,
        durationDays: 4,
        iconType: 'fertilizer',
      },
      {
        stage: 'Irrigation',
        title: 'Peak Flowering Irrigation',
        description: 'Critical moisture period. Moisture stress at flowering causes severe square and flower drop.',
        recommendation: 'Drip irrigation or furrow watering is optimal. Avoid flooding the root zone.',
        dayOffset: 75,
        durationDays: 4,
        iconType: 'irrigation',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Pink Bollworm (PBW) Monitoring',
        description: 'Check rosette flowers and inspect green bolls for internal larva entry holes.',
        recommendation: 'Install 4-5 PBW pheromone traps/acre. Spray Emamectin Benzoate 5 SG @ 0.5g/L if moth catch exceeds 8/trap/day.',
        dayOffset: 95,
        durationDays: 14,
        iconType: 'pest',
      },
      {
        stage: 'Fertilization',
        title: 'Boll Development Foliar Nutrition',
        description: 'Spray 00:52:34 (MKP) @ 10g/L + Boron 20% @ 1g/L to prevent boll shedding and improve fiber quality.',
        recommendation: 'Repeat spray 15 days later during heavy boll load.',
        dayOffset: 110,
        durationDays: 3,
        iconType: 'fertilizer',
      },
      {
        stage: 'Harvest',
        title: 'Boll Picking (1st & 2nd Pickings)',
        description: 'Pick fully opened, dry, clean bolls without bracts or dried leaves.',
        recommendation: 'Pick during sunny morning hours after dew has evaporated. Store in clean dry cotton bags.',
        dayOffset: 155,
        durationDays: 14,
        iconType: 'harvest',
      },
    ],
  },
  {
    id: 'maize',
    name: 'Maize / Corn (मक्का / મકાઈ)',
    category: 'Cereal',
    defaultSeason: 'Kharif',
    durationDays: 105,
    description: 'Versatile grain and fodder crop with fast growth cycle and high nutrient responsiveness.',
    activities: [
      {
        stage: 'Sowing',
        title: 'Field Preparation & Sowing',
        description: 'Sow at 60x20 cm spacing. Seed rate: 20 kg/ha. Treat with Azotobacter and PSB culture.',
        recommendation: 'Incorporate DAP (40 kg/acre) + MOP (20 kg/acre) as basal dose.',
        dayOffset: 0,
        durationDays: 3,
        iconType: 'sowing',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Fall Armyworm (FAW) Scouting',
        description: 'Scout whorls of young plants (knee-high stage) for pinholes, ragged leaf edges, and fresh frass.',
        recommendation: 'Apply Chlorantraniliprole 18.5 SC @ 0.4 ml/L directly into leaf whorls upon early detection.',
        dayOffset: 20,
        durationDays: 6,
        iconType: 'pest',
      },
      {
        stage: 'Fertilization',
        title: 'Knee-High Stage Top Dressing',
        description: 'Apply 1st split Urea (35 kg/acre) + Zinc Sulphate (5 kg/acre if not applied earlier).',
        recommendation: 'Perform inter-cultivation weeding and earthing up to prevent lodging.',
        dayOffset: 30,
        durationDays: 3,
        iconType: 'fertilizer',
      },
      {
        stage: 'Irrigation',
        title: 'Tasseling & Silking Irrigation',
        description: 'Most critical moisture phase. Water stress during tassel/silk emergence leads to poor seed set.',
        recommendation: 'Ensure adequate soil moisture until grain formation is complete.',
        dayOffset: 55,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Fertilization',
        title: 'Tasseling Stage Booster Dose',
        description: 'Apply final split of Urea (25 kg/acre) to support grain filling and cob weight.',
        recommendation: 'Broadcast fertilizer followed by light irrigation.',
        dayOffset: 60,
        durationDays: 2,
        iconType: 'fertilizer',
      },
      {
        stage: 'Harvest',
        title: 'Cob Harvesting & Sun Drying',
        description: 'Husks turn papery dry and brown; black layer forms at the base of grains.',
        recommendation: 'De-husk and dry cobs under direct sunlight to 12% moisture before mechanical shelling.',
        dayOffset: 100,
        durationDays: 5,
        iconType: 'harvest',
      },
    ],
  },
  {
    id: 'tomato',
    name: 'Tomato (टमाटर / ટામેટા)',
    category: 'Vegetable',
    defaultSeason: 'Rabi',
    durationDays: 115,
    description: 'High-value horticulture crop requiring careful staking, disease control, and balanced fertigation.',
    activities: [
      {
        stage: 'Sowing',
        title: 'Nursery Raising & Seedling Dip',
        description: 'Raise seedlings in pro-trays with coco peat. Dip seedling roots in Trichoderma (10g/L) before planting.',
        recommendation: 'Transplant 25-30 day healthy seedlings on raised beds with silver-black mulch at 60x45 cm.',
        dayOffset: 0,
        durationDays: 5,
        iconType: 'sowing',
      },
      {
        stage: 'Fertilization',
        title: 'Vegetative Fertigation & Staking',
        description: 'Provide 19:19:19 (3 kg/acre/week) through drip. Provide bamboo staking or trellising to support vines.',
        recommendation: 'Remove lower side suckers to encourage single/double stem vertical training.',
        dayOffset: 20,
        durationDays: 5,
        iconType: 'fertilizer',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Early Blight & Whitefly Monitoring',
        description: 'Check for concentric bullseye rings on bottom leaves and whiteflies transmitting leaf curl virus.',
        recommendation: 'Spray Mancozeb 75 WP @ 2.5g/L for blight. Install yellow sticky traps (10/acre) for whiteflies.',
        dayOffset: 35,
        durationDays: 7,
        iconType: 'pest',
      },
      {
        stage: 'Fertilization',
        title: 'Flowering & Fruit Set Nutrition',
        description: 'Apply Calcium Nitrate (4 kg/acre) + Boron (1 kg/acre) to prevent Blossom End Rot and fruit cracking.',
        recommendation: 'Switch fertigation to 12:61:00 or 13:40:13 during intense flower bud initiation.',
        dayOffset: 50,
        durationDays: 4,
        iconType: 'fertilizer',
      },
      {
        stage: 'Irrigation',
        title: 'Consistent Fruit Growth Irrigation',
        description: 'Maintain uniform soil moisture. Alternating drought and flooding causes severe fruit splitting.',
        recommendation: 'Irrigate daily or alternate days via drip in early mornings.',
        dayOffset: 65,
        durationDays: 15,
        iconType: 'irrigation',
      },
      {
        stage: 'Harvest',
        title: 'Breaker / Pink Stage Harvesting',
        description: 'Harvest tomatoes at breaker/pink stage for long-distance transport, or red-ripe for local sale.',
        recommendation: 'Harvest in cool morning hours. Handle gently in plastic crates to prevent bruising.',
        dayOffset: 95,
        durationDays: 20,
        iconType: 'harvest',
      },
    ],
  },
  {
    id: 'mustard',
    name: 'Mustard / Rapeseed (सरसों / રાયડો)',
    category: 'Oilseed',
    defaultSeason: 'Rabi',
    durationDays: 110,
    description: 'Major edible oilseed crop with high drought tolerance and high oil content.',
    activities: [
      {
        stage: 'Sowing',
        title: 'Land Preparation & Sowing',
        description: 'Conserve residual soil moisture. Sow at 30x10 cm spacing, 3-4 cm depth. Seed rate: 4-5 kg/ha.',
        recommendation: 'Incorporate Sulphur (20 kg/ha via SSP or Bentonite Sulphur) to increase seed oil percentage.',
        dayOffset: 0,
        durationDays: 3,
        iconType: 'sowing',
      },
      {
        stage: 'Irrigation',
        title: 'Branching Stage Irrigation',
        description: 'First irrigation at 30-35 days after sowing (vegetative branching stage).',
        recommendation: 'Thin out excess seedlings to keep 1 healthy plant every 10-12 cm in the row.',
        dayOffset: 30,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Fertilization',
        title: 'Top Dressing of Nitrogen',
        description: 'Apply remaining split of Urea (30 kg/acre) after the 1st irrigation.',
        recommendation: 'Ensure soil has enough moisture before broadcasting Urea.',
        dayOffset: 35,
        durationDays: 2,
        iconType: 'fertilizer',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Mustard Aphid Surveillance',
        description: 'Inspect flowering twigs and siliquae for aphid clustering, especially during cloudy/foggy spells.',
        recommendation: 'Spray Dimethoate 30 EC @ 1.7 ml/L or Thiamethoxam 25 WG @ 0.3g/L if 1.5 cm twig colonization is seen.',
        dayOffset: 60,
        durationDays: 10,
        iconType: 'pest',
      },
      {
        stage: 'Irrigation',
        title: 'Pod / Siliqua Formation Irrigation',
        description: 'Second critical irrigation during pod development to ensure full seed plumpness.',
        recommendation: 'Avoid over-irrigation which may cause white rust fungal proliferation.',
        dayOffset: 70,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Harvest',
        title: 'Harvesting & Siliqua Threshing',
        description: 'Harvest when 75% of pods turn golden yellowish-brown. Avoid delay to prevent pod shattering.',
        recommendation: 'Cut plants early morning when pods are moist with dew to minimize seed loss.',
        dayOffset: 105,
        durationDays: 5,
        iconType: 'harvest',
      },
    ],
  },
  {
    id: 'potato',
    name: 'Potato (आलू / બટાટા)',
    category: 'Vegetable',
    defaultSeason: 'Rabi',
    durationDays: 95,
    description: 'High yielding tuber crop thriving in well-drained friable sandy loam soils.',
    activities: [
      {
        stage: 'Sowing',
        title: 'Tuber Treatment & Planting on Ridges',
        description: 'Plant well-sprouted seed tubers (40-50g size) on ridges at 60x20 cm. Treat with Mancozeb (2.5g/L).',
        recommendation: 'Apply rich organic compost + basal NPK 12:32:16 (75 kg/acre).',
        dayOffset: 0,
        durationDays: 4,
        iconType: 'sowing',
      },
      {
        stage: 'Irrigation',
        title: 'Sprouting & Emergence Irrigation',
        description: 'Light irrigation to facilitate uniform shoot emergence. Keep ridges 2/3rd submerged only.',
        recommendation: 'Do not submerge the top of the ridge to prevent seed tuber rotting.',
        dayOffset: 10,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Fertilization',
        title: 'Earthing Up & 1st Top Dressing',
        description: 'Perform earthing up when plants are 15-20 cm high. Apply Urea (40 kg/acre) + Potash (20 kg/acre).',
        recommendation: 'Proper earthing up prevents exposure of growing tubers to sunlight (greening of potatoes).',
        dayOffset: 30,
        durationDays: 4,
        iconType: 'fertilizer',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Late Blight Disease Scouting',
        description: 'Watch for water-soaked lesions on leaf margins with white mildew under humid overcast conditions.',
        recommendation: 'Prophylactic spray of Mancozeb 75 WP (2.5g/L); switch to Cymoxanil + Mancozeb if symptoms appear.',
        dayOffset: 45,
        durationDays: 14,
        iconType: 'pest',
      },
      {
        stage: 'Fertilization',
        title: 'Tuber Bulking Nutrition & Irrigation',
        description: 'Foliar spray of 00:00:50 (Potassium Sulphate) @ 10g/L to maximize tuber size and solid content.',
        recommendation: 'Maintain steady moisture until dehaulming.',
        dayOffset: 60,
        durationDays: 4,
        iconType: 'fertilizer',
      },
      {
        stage: 'Harvest',
        title: 'Dehaulming & Curing / Harvest',
        description: 'Cut vine canopy (dehaulming) 10-12 days before digging to harden tuber skins.',
        recommendation: 'Dig tubers gently in dry soil. Cure in shade for 7-10 days before grading and storage.',
        dayOffset: 90,
        durationDays: 6,
        iconType: 'harvest',
      },
    ],
  },
]

export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Gujarat',
  'Haryana',
  'Karnataka',
  'Madhya Pradesh',
  'Maharashtra',
  'Punjab',
  'Rajasthan',
  'Tamil Nadu',
  'Telangana',
  'Uttar Pradesh',
  'West Bengal',
  'Other / Global',
]

export function computeActivityDate(sowingDateStr: string, dayOffset: number, customDate?: string): { dateStr: string; displayStr: string; isPast: boolean; isToday: boolean; daysRemaining: number } {
  const targetDate = customDate ? new Date(customDate) : new Date(new Date(sowingDateStr).getTime() + dayOffset * 24 * 60 * 60 * 1000)
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  targetDate.setHours(0, 0, 0, 0)

  const diffTime = targetDate.getTime() - today.getTime()
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24))

  const dateStr = targetDate.toISOString().slice(0, 10)
  const displayStr = targetDate.toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })

  return {
    dateStr,
    displayStr,
    isPast: diffDays < 0,
    isToday: diffDays === 0,
    daysRemaining: diffDays,
  }
}

export function generateCustomPlan(cropName: string, season: 'Kharif' | 'Rabi' | 'Zaid'): CropTemplate {
  return {
    id: 'custom-' + cropName.toLowerCase().replace(/\s+/g, '-'),
    name: cropName,
    category: 'Cereal',
    defaultSeason: season,
    durationDays: 120,
    description: `Customized agricultural schedule for ${cropName} (${season} season).`,
    activities: [
      {
        stage: 'Sowing',
        title: 'Soil Preparation & Sowing',
        description: `Tillage, basal nutrient application, and seed/sapling planting for ${cropName}.`,
        recommendation: 'Treat seeds with bio-inoculants (Trichoderma/Rhizobium) before planting.',
        dayOffset: 0,
        durationDays: 5,
        iconType: 'sowing',
      },
      {
        stage: 'Irrigation',
        title: 'Initial Crop Establishment Irrigation',
        description: 'First scheduled irrigation to ensure healthy seed germination and early root formation.',
        recommendation: 'Check soil moisture depth before watering.',
        dayOffset: 15,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Fertilization',
        title: 'Early Vegetative Fertilizer Application',
        description: 'Apply top dressing of balanced nitrogen and micronutrients for vigorous leaf canopy growth.',
        recommendation: 'Apply fertilizer in moist soil condition.',
        dayOffset: 30,
        durationDays: 3,
        iconType: 'fertilizer',
      },
      {
        stage: 'Pest Monitoring',
        title: 'Mid-Season Pest & Disease Scouting',
        description: 'Scout upper and lower leaf surfaces for chewing/sucking pests and leaf spot diseases.',
        recommendation: 'Use sticky traps and organic neem spray as first-line preventative measures.',
        dayOffset: 55,
        durationDays: 7,
        iconType: 'pest',
      },
      {
        stage: 'Fertilization',
        title: 'Flowering & Reproductive Phase Nutrition',
        description: 'Provide potassium and phosphorus boost to enhance reproductive setting and yield quality.',
        recommendation: 'Foliar spray with water-soluble nutrients during cool hours.',
        dayOffset: 70,
        durationDays: 3,
        iconType: 'fertilizer',
      },
      {
        stage: 'Irrigation',
        title: 'Final Pod/Fruit/Grain Filling Irrigation',
        description: 'Maintain uniform moisture during critical filling stage to avoid grain shriveling.',
        recommendation: 'Stop irrigation 10-14 days before harvest.',
        dayOffset: 90,
        durationDays: 3,
        iconType: 'irrigation',
      },
      {
        stage: 'Harvest',
        title: 'Maturity Inspection & Harvesting',
        description: `Harvest ${cropName} upon full physiological maturity when moisture level is optimal.`,
        recommendation: 'Dry and clean produce thoroughly before storing in moisture-proof containers.',
        dayOffset: 120,
        durationDays: 7,
        iconType: 'harvest',
      },
    ],
  }
}
